package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Agence generated by hbm2java
 */
public class Agence implements java.io.Serializable {

	private Integer idAg;
	private String nameAg;
	private String addressAg;
	private byte[] geolocAg;
	private Set managers = new HashSet(0);

	public Agence() {
	}

	public Agence(String nameAg, String addressAg, byte[] geolocAg) {
		this.nameAg = nameAg;
		this.addressAg = addressAg;
		this.geolocAg = geolocAg;
	}

	public Agence(String nameAg, String addressAg, byte[] geolocAg, Set managers) {
		this.nameAg = nameAg;
		this.addressAg = addressAg;
		this.geolocAg = geolocAg;
		this.managers = managers;
	}

	public Integer getIdAg() {
		return this.idAg;
	}

	public void setIdAg(Integer idAg) {
		this.idAg = idAg;
	}

	public String getNameAg() {
		return this.nameAg;
	}

	public void setNameAg(String nameAg) {
		this.nameAg = nameAg;
	}

	public String getAddressAg() {
		return this.addressAg;
	}

	public void setAddressAg(String addressAg) {
		this.addressAg = addressAg;
	}

	public byte[] getGeolocAg() {
		return this.geolocAg;
	}

	public void setGeolocAg(byte[] geolocAg) {
		this.geolocAg = geolocAg;
	}

	public Set getManagers() {
		return this.managers;
	}

	public void setManagers(Set managers) {
		this.managers = managers;
	}

}
