package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

/**
 * DriveId generated by hbm2java
 */
public class DriveId implements java.io.Serializable {

	private String immatTru;
	private int idVeh;
	private int idUser;

	public DriveId() {
	}

	public DriveId(String immatTru, int idVeh, int idUser) {
		this.immatTru = immatTru;
		this.idVeh = idVeh;
		this.idUser = idUser;
	}

	public String getImmatTru() {
		return this.immatTru;
	}

	public void setImmatTru(String immatTru) {
		this.immatTru = immatTru;
	}

	public int getIdVeh() {
		return this.idVeh;
	}

	public void setIdVeh(int idVeh) {
		this.idVeh = idVeh;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DriveId))
			return false;
		DriveId castOther = (DriveId) other;

		return ((this.getImmatTru() == castOther.getImmatTru()) || (this.getImmatTru() != null
				&& castOther.getImmatTru() != null && this.getImmatTru().equals(castOther.getImmatTru())))
				&& (this.getIdVeh() == castOther.getIdVeh()) && (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImmatTru() == null ? 0 : this.getImmatTru().hashCode());
		result = 37 * result + this.getIdVeh();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
