package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

/**
 * IncidentId generated by hbm2java
 */
public class IncidentId implements java.io.Serializable {

	private int idInt;
	private String immatTru;
	private int idVeh;

	public IncidentId() {
	}

	public IncidentId(int idInt, String immatTru, int idVeh) {
		this.idInt = idInt;
		this.immatTru = immatTru;
		this.idVeh = idVeh;
	}

	public int getIdInt() {
		return this.idInt;
	}

	public void setIdInt(int idInt) {
		this.idInt = idInt;
	}

	public String getImmatTru() {
		return this.immatTru;
	}

	public void setImmatTru(String immatTru) {
		this.immatTru = immatTru;
	}

	public int getIdVeh() {
		return this.idVeh;
	}

	public void setIdVeh(int idVeh) {
		this.idVeh = idVeh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IncidentId))
			return false;
		IncidentId castOther = (IncidentId) other;

		return (this.getIdInt() == castOther.getIdInt())
				&& ((this.getImmatTru() == castOther.getImmatTru()) || (this.getImmatTru() != null
						&& castOther.getImmatTru() != null && this.getImmatTru().equals(castOther.getImmatTru())))
				&& (this.getIdVeh() == castOther.getIdVeh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdInt();
		result = 37 * result + (getImmatTru() == null ? 0 : this.getImmatTru().hashCode());
		result = 37 * result + this.getIdVeh();
		return result;
	}

}
