package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

/**
 * Incident generated by hbm2java
 */
public class Incident implements java.io.Serializable {

	private IncidentId id;
	private Intervention intervention;
	private Vehicle vehicle;
	private VehicleModel vehicleModel;

	public Incident() {
	}

	public Incident(IncidentId id, Intervention intervention, Vehicle vehicle, VehicleModel vehicleModel) {
		this.id = id;
		this.intervention = intervention;
		this.vehicle = vehicle;
		this.vehicleModel = vehicleModel;
	}

	public IncidentId getId() {
		return this.id;
	}

	public void setId(IncidentId id) {
		this.id = id;
	}

	public Intervention getIntervention() {
		return this.intervention;
	}

	public void setIntervention(Intervention intervention) {
		this.intervention = intervention;
	}

	public Vehicle getVehicle() {
		return this.vehicle;
	}

	public void setVehicle(Vehicle vehicle) {
		this.vehicle = vehicle;
	}

	public VehicleModel getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(VehicleModel vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

}
