package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Intervention generated by hbm2java
 */
public class Intervention implements java.io.Serializable {

	private int idInt;
	private Date hourStartInt;
	private Date hourEndInt;
	private double latInt;
	private double longInt;
	private Set incidents = new HashSet(0);
	private Set users = new HashSet(0);

	public Intervention() {
	}

	public Intervention(int idInt, Date hourStartInt, double latInt, double longInt) {
		this.idInt = idInt;
		this.hourStartInt = hourStartInt;
		this.latInt = latInt;
		this.longInt = longInt;
	}

	public Intervention(int idInt, Date hourStartInt, Date hourEndInt, double latInt, double longInt, Set incidents,
			Set users) {
		this.idInt = idInt;
		this.hourStartInt = hourStartInt;
		this.hourEndInt = hourEndInt;
		this.latInt = latInt;
		this.longInt = longInt;
		this.incidents = incidents;
		this.users = users;
	}

	public int getIdInt() {
		return this.idInt;
	}

	public void setIdInt(int idInt) {
		this.idInt = idInt;
	}

	public Date getHourStartInt() {
		return this.hourStartInt;
	}

	public void setHourStartInt(Date hourStartInt) {
		this.hourStartInt = hourStartInt;
	}

	public Date getHourEndInt() {
		return this.hourEndInt;
	}

	public void setHourEndInt(Date hourEndInt) {
		this.hourEndInt = hourEndInt;
	}

	public double getLatInt() {
		return this.latInt;
	}

	public void setLatInt(double latInt) {
		this.latInt = latInt;
	}

	public double getLongInt() {
		return this.longInt;
	}

	public void setLongInt(double longInt) {
		this.longInt = longInt;
	}

	public Set getIncidents() {
		return this.incidents;
	}

	public void setIncidents(Set incidents) {
		this.incidents = incidents;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
