package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

/**
 * Manager generated by hbm2java
 */
public class Manager implements java.io.Serializable {

	private int idUser;
	private Agence agence;
	private User user;

	public Manager() {
	}

	public Manager(User user) {
		this.user = user;
	}

	public Manager(Agence agence, User user) {
		this.agence = agence;
		this.user = user;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public Agence getAgence() {
		return this.agence;
	}

	public void setAgence(Agence agence) {
		this.agence = agence;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
