package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Mission generated by hbm2java
 */
public class Mission implements java.io.Serializable {

	private Integer idMis;
	private User user;
	private Date hourStartMis;
	private Date hourEndMis;
	private String nameSenMis;
	private String nameRecMis;
	private String qualitySenMis;
	private String qualityRecMis;
	private int numSenMis;
	private int numRecMis;
	private double latMis;
	private double longMis;
	private String state;
	private Set users = new HashSet(0);

	public Mission() {
	}

	public Mission(User user, Date hourStartMis, String nameSenMis, String nameRecMis, String qualitySenMis,
			String qualityRecMis, int numSenMis, int numRecMis, double latMis, double longMis) {
		this.user = user;
		this.hourStartMis = hourStartMis;
		this.nameSenMis = nameSenMis;
		this.nameRecMis = nameRecMis;
		this.qualitySenMis = qualitySenMis;
		this.qualityRecMis = qualityRecMis;
		this.numSenMis = numSenMis;
		this.numRecMis = numRecMis;
		this.latMis = latMis;
		this.longMis = longMis;
	}

	public Mission(User user, Date hourStartMis, Date hourEndMis, String nameSenMis, String nameRecMis,
			String qualitySenMis, String qualityRecMis, int numSenMis, int numRecMis, double latMis, double longMis,
			String state, Set users) {
		this.user = user;
		this.hourStartMis = hourStartMis;
		this.hourEndMis = hourEndMis;
		this.nameSenMis = nameSenMis;
		this.nameRecMis = nameRecMis;
		this.qualitySenMis = qualitySenMis;
		this.qualityRecMis = qualityRecMis;
		this.numSenMis = numSenMis;
		this.numRecMis = numRecMis;
		this.latMis = latMis;
		this.longMis = longMis;
		this.state = state;
		this.users = users;
	}

	public Integer getIdMis() {
		return this.idMis;
	}

	public void setIdMis(Integer idMis) {
		this.idMis = idMis;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Date getHourStartMis() {
		return this.hourStartMis;
	}

	public void setHourStartMis(Date hourStartMis) {
		this.hourStartMis = hourStartMis;
	}

	public Date getHourEndMis() {
		return this.hourEndMis;
	}

	public void setHourEndMis(Date hourEndMis) {
		this.hourEndMis = hourEndMis;
	}

	public String getNameSenMis() {
		return this.nameSenMis;
	}

	public void setNameSenMis(String nameSenMis) {
		this.nameSenMis = nameSenMis;
	}

	public String getNameRecMis() {
		return this.nameRecMis;
	}

	public void setNameRecMis(String nameRecMis) {
		this.nameRecMis = nameRecMis;
	}

	public String getQualitySenMis() {
		return this.qualitySenMis;
	}

	public void setQualitySenMis(String qualitySenMis) {
		this.qualitySenMis = qualitySenMis;
	}

	public String getQualityRecMis() {
		return this.qualityRecMis;
	}

	public void setQualityRecMis(String qualityRecMis) {
		this.qualityRecMis = qualityRecMis;
	}

	public int getNumSenMis() {
		return this.numSenMis;
	}

	public void setNumSenMis(int numSenMis) {
		this.numSenMis = numSenMis;
	}

	public int getNumRecMis() {
		return this.numRecMis;
	}

	public void setNumRecMis(int numRecMis) {
		this.numRecMis = numRecMis;
	}

	public double getLatMis() {
		return this.latMis;
	}

	public void setLatMis(double latMis) {
		this.latMis = latMis;
	}

	public double getLongMis() {
		return this.longMis;
	}

	public void setLongMis(double longMis) {
		this.longMis = longMis;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

}
