package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer idUser;
	private String mailUser;
	private String passUser;
	private Integer rightUser;
	private double hoursWork;
	private double hoursBreak;
	private String firstnameUser;
	private String lastnameUser;
	private Set licences = new HashSet(0);
	private TruckDriver truckDriver;
	private Set missions = new HashSet(0);
	private Set interventions = new HashSet(0);
	private Manager manager;
	private Set missions_1 = new HashSet(0);
	private Driver driver;
	private Set usersForIdUser = new HashSet(0);
	private InterventionAgent interventionAgent;
	private Set usersForIdUser1 = new HashSet(0);
	private Set drives = new HashSet(0);

	public User() {
	}

	public User(double hoursWork, double hoursBreak, String firstnameUser) {
		this.hoursWork = hoursWork;
		this.hoursBreak = hoursBreak;
		this.firstnameUser = firstnameUser;
	}

	public User(String mailUser, String passUser, Integer rightUser, double hoursWork, double hoursBreak,
			String firstnameUser, String lastnameUser, Set licences, TruckDriver truckDriver, Set missions,
			Set interventions, Manager manager, Set missions_1, Driver driver, Set usersForIdUser,
			InterventionAgent interventionAgent, Set usersForIdUser1, Set drives) {
		this.mailUser = mailUser;
		this.passUser = passUser;
		this.rightUser = rightUser;
		this.hoursWork = hoursWork;
		this.hoursBreak = hoursBreak;
		this.firstnameUser = firstnameUser;
		this.lastnameUser = lastnameUser;
		this.licences = licences;
		this.truckDriver = truckDriver;
		this.missions = missions;
		this.interventions = interventions;
		this.manager = manager;
		this.missions_1 = missions_1;
		this.driver = driver;
		this.usersForIdUser = usersForIdUser;
		this.interventionAgent = interventionAgent;
		this.usersForIdUser1 = usersForIdUser1;
		this.drives = drives;
	}

	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	public String getMailUser() {
		return this.mailUser;
	}

	public void setMailUser(String mailUser) {
		this.mailUser = mailUser;
	}

	public String getPassUser() {
		return this.passUser;
	}

	public void setPassUser(String passUser) {
		this.passUser = passUser;
	}

	public Integer getRightUser() {
		return this.rightUser;
	}

	public void setRightUser(Integer rightUser) {
		this.rightUser = rightUser;
	}

	public double getHoursWork() {
		return this.hoursWork;
	}

	public void setHoursWork(double hoursWork) {
		this.hoursWork = hoursWork;
	}

	public double getHoursBreak() {
		return this.hoursBreak;
	}

	public void setHoursBreak(double hoursBreak) {
		this.hoursBreak = hoursBreak;
	}

	public String getFirstnameUser() {
		return this.firstnameUser;
	}

	public void setFirstnameUser(String firstnameUser) {
		this.firstnameUser = firstnameUser;
	}

	public String getLastnameUser() {
		return this.lastnameUser;
	}

	public void setLastnameUser(String lastnameUser) {
		this.lastnameUser = lastnameUser;
	}

	public Set getLicences() {
		return this.licences;
	}

	public void setLicences(Set licences) {
		this.licences = licences;
	}

	public TruckDriver getTruckDriver() {
		return this.truckDriver;
	}

	public void setTruckDriver(TruckDriver truckDriver) {
		this.truckDriver = truckDriver;
	}

	public Set getMissions() {
		return this.missions;
	}

	public void setMissions(Set missions) {
		this.missions = missions;
	}

	public Set getInterventions() {
		return this.interventions;
	}

	public void setInterventions(Set interventions) {
		this.interventions = interventions;
	}

	public Manager getManager() {
		return this.manager;
	}

	public void setManager(Manager manager) {
		this.manager = manager;
	}

	public Set getMissions_1() {
		return this.missions_1;
	}

	public void setMissions_1(Set missions_1) {
		this.missions_1 = missions_1;
	}

	public Driver getDriver() {
		return this.driver;
	}

	public void setDriver(Driver driver) {
		this.driver = driver;
	}

	public Set getUsersForIdUser() {
		return this.usersForIdUser;
	}

	public void setUsersForIdUser(Set usersForIdUser) {
		this.usersForIdUser = usersForIdUser;
	}

	public InterventionAgent getInterventionAgent() {
		return this.interventionAgent;
	}

	public void setInterventionAgent(InterventionAgent interventionAgent) {
		this.interventionAgent = interventionAgent;
	}

	public Set getUsersForIdUser1() {
		return this.usersForIdUser1;
	}

	public void setUsersForIdUser1(Set usersForIdUser1) {
		this.usersForIdUser1 = usersForIdUser1;
	}

	public Set getDrives() {
		return this.drives;
	}

	public void setDrives(Set drives) {
		this.drives = drives;
	}

}
