package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VehicleModel generated by hbm2java
 */
public class VehicleModel implements java.io.Serializable {

	private Integer idVeh;
	private Licence licence;
	private String libelleVeh;
	private int speedMaxVeh;
	private Set drives = new HashSet(0);
	private Set vehicles = new HashSet(0);
	private Set incidents = new HashSet(0);

	public VehicleModel() {
	}

	public VehicleModel(String libelleVeh, int speedMaxVeh) {
		this.libelleVeh = libelleVeh;
		this.speedMaxVeh = speedMaxVeh;
	}

	public VehicleModel(Licence licence, String libelleVeh, int speedMaxVeh, Set drives, Set vehicles, Set incidents) {
		this.licence = licence;
		this.libelleVeh = libelleVeh;
		this.speedMaxVeh = speedMaxVeh;
		this.drives = drives;
		this.vehicles = vehicles;
		this.incidents = incidents;
	}

	public Integer getIdVeh() {
		return this.idVeh;
	}

	public void setIdVeh(Integer idVeh) {
		this.idVeh = idVeh;
	}

	public Licence getLicence() {
		return this.licence;
	}

	public void setLicence(Licence licence) {
		this.licence = licence;
	}

	public String getLibelleVeh() {
		return this.libelleVeh;
	}

	public void setLibelleVeh(String libelleVeh) {
		this.libelleVeh = libelleVeh;
	}

	public int getSpeedMaxVeh() {
		return this.speedMaxVeh;
	}

	public void setSpeedMaxVeh(int speedMaxVeh) {
		this.speedMaxVeh = speedMaxVeh;
	}

	public Set getDrives() {
		return this.drives;
	}

	public void setDrives(Set drives) {
		this.drives = drives;
	}

	public Set getVehicles() {
		return this.vehicles;
	}

	public void setVehicles(Set vehicles) {
		this.vehicles = vehicles;
	}

	public Set getIncidents() {
		return this.incidents;
	}

	public void setIncidents(Set incidents) {
		this.incidents = incidents;
	}

}
