package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehicle generated by hbm2java
 */
public class Vehicle implements java.io.Serializable {

	private VehicleId id;
	private VehicleModel vehicleModel;
	private Date ctrlTechTru;
	private byte[] areaTru;
	private Integer etat;
	private Set drives = new HashSet(0);
	private Set incidents = new HashSet(0);

	public Vehicle() {
	}

	public Vehicle(VehicleId id, VehicleModel vehicleModel) {
		this.id = id;
		this.vehicleModel = vehicleModel;
	}

	public Vehicle(VehicleId id, VehicleModel vehicleModel, Date ctrlTechTru, byte[] areaTru, Integer etat, Set drives,
			Set incidents) {
		this.id = id;
		this.vehicleModel = vehicleModel;
		this.ctrlTechTru = ctrlTechTru;
		this.areaTru = areaTru;
		this.etat = etat;
		this.drives = drives;
		this.incidents = incidents;
	}

	public VehicleId getId() {
		return this.id;
	}

	public VehicleModel getVehicleModel() {
		return this.vehicleModel;
	}

	public void setVehicleModel(VehicleModel vehicleModel) {
		this.vehicleModel = vehicleModel;
	}

	public Date getCtrlTechTru() {
		return this.ctrlTechTru;
	}

	public void setCtrlTechTru(Date ctrlTechTru) {
		this.ctrlTechTru = ctrlTechTru;
	}

	public byte[] getAreaTru() {
		return this.areaTru;
	}

	public void setAreaTru(byte[] areaTru) {
		this.areaTru = areaTru;
	}

	public Integer getEtat() {
		return this.etat;
	}

	public void setEtat(Integer etat) {
		this.etat = etat;
	}

	public Set getDrives() {
		return this.drives;
	}

	public void setDrives(Set drives) {
		this.drives = drives;
	}

	public Set getIncidents() {
		return this.incidents;
	}

	public void setIncidents(Set incidents) {
		this.incidents = incidents;
	}

}
