package com.trucky.Domain;
// Generated 12 janv. 2017 09:28:27 by Hibernate Tools 5.2.0.CR1

/**
 * VehicleId generated by hbm2java
 */
@SuppressWarnings("serial")
public class VehicleId implements java.io.Serializable {

	private String immatTru;
	private int idVeh;

	public VehicleId(String immatTru, int idVeh) {
		this.immatTru = immatTru;
		this.idVeh = idVeh;
	}

	public String getImmatTru() {
		return this.immatTru;
	}

	public void setImmatTru(String immatTru) {
		this.immatTru = immatTru;
	}

	public int getIdVeh() {
		return this.idVeh;
	}

	public void setIdVeh(int idVeh) {
		this.idVeh = idVeh;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VehicleId))
			return false;
		VehicleId castOther = (VehicleId) other;

		return ((this.getImmatTru() == castOther.getImmatTru()) || (this.getImmatTru() != null
				&& castOther.getImmatTru() != null && this.getImmatTru().equals(castOther.getImmatTru())))
				&& (this.getIdVeh() == castOther.getIdVeh());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getImmatTru() == null ? 0 : this.getImmatTru().hashCode());
		result = 37 * result + this.getIdVeh();
		return result;
	}

}
